#!/usr/bin/env bash
# Script that configures and sets up HAProxy(Load Balancing) servers
# using the RoundRobin algorithm
sudo apt-get -y update
sudo apt-get -y install haproxy

host1=$(curl -sI 34.231.147.175 | grep X-Served-By | awk '{ print $2 }' | rev | cut -c 2- | rev)
host2=$(curl -sI 3.236.254.207 | grep X-Served-By | awk '{ print $2 }' | rev | cut -c 2- | rev)

sudo cat >> /etc/haproxy/haproxy.cfg << EOF
frontend main
	mode http
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server ${host1} 34.231.147.175:80 check
	server ${host2} 3.236.254.207:80 check

EOF

echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
